---
hyperparameters: 
  mixed_precision: False
  weight_loss: False
  weight_init: 0.02
  optimiser:
    name: AdamW
    betas: 
      - 0.9
      - 0.999
    weight_decay: 0.0 
  label_smoothing: 0.0
  batch_size: 1024
  grad_accumulation: 1
  schedules:
    lr: 
    name: warmup_cosine
    ref_val: 1e-05
    start_val: 1e-06
    end_val: 1e-06 
    warmup_steps: 20
    T_max: 200
  warmup_epochs: 20
  training_epochs: 200
  batch_aug: None
  final_layer_activation: True
dataset:
  name: lycos2017
  tabular: True
  data_path: ~/data/lycos.csv
  drop: 
    - flow_id
    - src_addr
    - src_port
    - dst_addr
    - dst_port
    - ip_prot
    - timestamp
  n_features: 72
  n_classes: 12
  n_numeric: 72
  n_cat: 0
  n_cats: []
  sample_thres: 100
  train_ratio: 0.5
  val_ratio: 0.0
  test_ratio: 0.5
  split_seed: 39058032
  train_drop_last: True
  target: label
  class_zero: benign
  batch_size: 1024
  balance_train: True
  return_zero_day': True
  return_data: False
  device: cuda
model: 
  name: contrastive_mlp
  d_in: 72
  d_out: 64
  n_classes: 12
  neurons: 
    - 1024
    - 1024
    - 1024
    - 1024
  activation: relu
  dropout: 0.0
  residual: True
  gated: False
  norm_layer: null
  block_norm: False
  layer_scale: null
loss:
  name: contrastive_anomaly
  m: 0.3
  squared: True
  distance_metric: cosine
  eps: 1e-06
  batch_aug: null
config_ovr: None 
device: cuda 
zd_classes': [10, 11]